# Import necessary libraries
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np # Used for handling potential NaN values
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# --- Simulate the results from your code ---
# In a real scenario, you would replace this section with the actual
# `results` dictionary generated by your HDBSCAN script.
# This example structure mirrors the output of your script.
results = {'HDBScan': {5: {'amount_noise': 0.3322,               ## cosine distance results
                 'davies_bouldin_score': 3.597158238633628,
                 'n_clusters': 4,
                 'silhouette_score': 0.11701963715593938},
             10: {'amount_noise': 0.5269,
                  'davies_bouldin_score': 4.630143665062779,
                  'n_clusters': 2,
                  'silhouette_score': 0.04318475663189831},
             25: {'amount_noise': 0.9567,
                  'davies_bouldin_score': 3.998098329308123,
                  'n_clusters': 2,
                  'silhouette_score': -0.18617244306718875},
             50: {'amount_noise': 0.9788,
                  'davies_bouldin_score': 3.670329186756009,
                  'n_clusters': 2,
                  'silhouette_score': -0.20182084013280074},
             100: {'amount_noise': 1.0,
                   'davies_bouldin_score': None,
                   'n_clusters': 0,
                   'silhouette_score': None},
             250: {'amount_noise': 1.0,
                   'davies_bouldin_score': None,
                   'n_clusters': 0,
                   'silhouette_score': None}}}

# results = {'HDBScan': {5: {'amount_noise': 0.3756,                            ##use these results for eucliean
#                  'davies_bouldin_score': 4.370471010894852,
#                  'n_clusters': 2,
#                  'silhouette_score': 0.10648375604271174},
#              10: {'amount_noise': 0.5731,
#                   'davies_bouldin_score': 4.876057445809022,
#                   'n_clusters': 2,
#                   'silhouette_score': 0.015282441315900525},
#              25: {'amount_noise': 0.9862,
#                   'davies_bouldin_score': 4.340003542841748,
#                   'n_clusters': 2,
#                   'silhouette_score': -0.23597706592551435},
#              50: {'amount_noise': 1.0,
#                   'davies_bouldin_score': None,
#                   'n_clusters': 0,
#                   'silhouette_score': None},
#              100: {'amount_noise': 1.0,
#                    'davies_bouldin_score': None,
#                    'n_clusters': 0,
#                    'silhouette_score': None},
#              250: {'amount_noise': 1.0,
#                    'davies_bouldin_score': None,
#                    'n_clusters': 0,
#                    'silhouette_score': None}}}



# Extract data for plotting from the results dictionary
min_cluster_sizes = sorted(results['HDBScan'].keys()) # Get the parameter values tested


# Extract each metric into its own list
n_clusters = [results['HDBScan'][mcs]['n_clusters'] for mcs in min_cluster_sizes]
amount_noise = [results['HDBScan'][mcs]['amount_noise'] for mcs in min_cluster_sizes]

# Keep track of original None positions and replace with NaN for line plotting
silhouette_scores_orig = [results['HDBScan'][mcs]['silhouette_score'] for mcs in min_cluster_sizes]
db_scores_orig = [results['HDBScan'][mcs]['davies_bouldin_score'] for mcs in min_cluster_sizes]

silhouette_scores_plot = [s if s is not None else np.nan for s in silhouette_scores_orig]
db_scores_plot = [db if db is not None else np.nan for db in db_scores_orig]

# Create lists of points where original score was None
mcs_sil_none = [mcs for mcs, s in zip(min_cluster_sizes, silhouette_scores_orig) if s is None]
mcs_db_none = [mcs for mcs, db in zip(min_cluster_sizes, db_scores_orig) if db is None]

# --- Plotting Section ---

# Use a more basic style, closer to default Matplotlib
plt.style.use('default') # Reset to default style

# Create a figure and a set of subplots (2 rows, 2 columns)
# Increased figure width for better x-axis spacing
fig, axes = plt.subplots(2, 2, figsize=(17, 10)) # Adjusted figsize slightly

# Add a main title to the figure
# Adjusted y position slightly if needed, but tight_layout rect is primary fix
fig.suptitle('HDBSCAN Parameter Tuning Results (Cosine Distance)', fontsize=16)

# --- Plot 1: Number of Clusters ---
axes[0, 0].plot(min_cluster_sizes, n_clusters, marker='o', linestyle='-', label='Clusters Found')
axes[0, 0].set_title('Number of Clusters vs. min_cluster_size')
axes[0, 0].set_xlabel('min_cluster_size')
axes[0, 0].set_ylabel('Number of Clusters')
# Force standard number formatting on y-axis (no scientific notation)
axes[0, 0].yaxis.set_major_formatter(mticker.ScalarFormatter())
axes[0, 0].yaxis.get_major_formatter().set_scientific(False)
axes[0, 0].yaxis.get_major_formatter().set_useOffset(False)
# Add markers for zero clusters
mcs_zero_clusters = [mcs for mcs, n in zip(min_cluster_sizes, n_clusters) if n == 0]
if mcs_zero_clusters:
    axes[0, 0].scatter(mcs_zero_clusters, [0]*len(mcs_zero_clusters), color='red', marker='x', s=100, zorder=5, label='Zero Clusters Found')
axes[0, 0].legend()
axes[0, 0].grid(True, linestyle=':')
axes[0, 0].set_xticks(min_cluster_sizes) # Show all tested sizes on x-axis if reasonable

# --- Plot 2: Amount of Noise ---
axes[0, 1].plot(min_cluster_sizes, amount_noise, marker='s', linestyle='--', label='Noise Proportion') # Changed marker/linestyle
axes[0, 1].set_title('Proportion of Noise vs. min_cluster_size')
axes[0, 1].set_xlabel('min_cluster_size')
axes[0, 1].set_ylabel('Proportion of Noise')
axes[0, 1].legend()
axes[0, 1].grid(True, linestyle=':')
axes[0, 1].set_xticks(min_cluster_sizes)

# --- Plot 3: Silhouette Score ---
axes[1, 0].plot(min_cluster_sizes, silhouette_scores_plot, marker='^', linestyle='-', label='Silhouette Score') # Changed marker
axes[1, 0].set_title('Silhouette Score vs. min_cluster_size (Higher is Better)')
axes[1, 0].set_xlabel('min_cluster_size')
axes[1, 0].set_ylabel('Silhouette Score')
# Add reference lines for theoretical bounds
axes[1, 0].axhline(1, color='grey', linestyle=':', linewidth=1, label='Theoretical Max (1.0)')
axes[1, 0].axhline(-1, color='grey', linestyle=':', linewidth=1, label='Theoretical Min (-1.0)')
axes[1, 0].axhline(0, color='lightgrey', linestyle='--', linewidth=0.8) # Reference for zero score
# Add markers where score was None (could not be calculated)
if mcs_sil_none:
    # Plot these markers at y=0 for visibility, adjust if needed
    axes[1, 0].scatter(mcs_sil_none, [0]*len(mcs_sil_none), color='red', marker='x', s=100, zorder=5, label='Score Not Calculated')
axes[1, 0].legend()
axes[1, 0].grid(True, linestyle=':')
axes[1, 0].set_xticks(min_cluster_sizes)

# --- Plot 4: Davies-Bouldin Score ---
axes[1, 1].plot(min_cluster_sizes, db_scores_plot, marker='x', linestyle='-', label='DB Score') # Changed marker
axes[1, 1].set_title('Davies-Bouldin Score vs. min_cluster_size (Lower is Better)')
axes[1, 1].set_xlabel('min_cluster_size')
axes[1, 1].set_ylabel('Davies-Bouldin Score')
# Add markers where score was None (could not be calculated)
if mcs_db_none:
    # Plot these markers near the bottom of the y-axis range for visibility
    min_y = min(db for db in db_scores_plot if not np.isnan(db)) if not all(np.isnan(db) for db in db_scores_plot) else 0
    axes[1, 1].scatter(mcs_db_none, [min_y]*len(mcs_db_none), color='red', marker='x', s=100, zorder=5, label='Score Not Calculated')
axes[1, 1].legend()
axes[1, 1].grid(True, linestyle=':')
axes[1, 1].set_xticks(min_cluster_sizes)

# Adjust layout to prevent labels/titles from overlapping
# Reduced the top value in rect (from 0.97 to 0.95) to give more space for suptitle
plt.tight_layout(rect=[0, 0, 1, 0.95])


# Display the plots
fig.savefig('HDBScan_graphsCosine.png', dpi=300)

plt.show()

# Optionally, save the figure to a file
