#!/bin/bash

#SBATCH --job-name=EEG_CF_Test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=06:00:0
#SBATCH --output=model.out
#SBATCH --account=COMS035104
#SBATCH --partition=gpu_short

# Run the executable

module load languages/python

python contentFunctionOptuna.py